import dayjs from "../lib/dayjs";

const monthEntryDate = (day, hour, minute = 0) =>
	dayjs().startOf("month").date(day).hour(hour).minute(minute).second(0);

const paleProjectPalette = [
	"#eff6ff",
	"#f0fdf4",
	"#fdf4ff",
	"#fefce8",
	"#f0fdfa",
	"#fff7ed",
	"#f5f3ff",
	"#fef2f2",
	"#ecfeff",
	"#f7fee7",
	"#faf5ff",
	"#f8fafc",
];

function hashString(value) {
	const text = String(value || "unknown")
		.trim()
		.toLowerCase();
	let hash = 2166136261;

	for (let index = 0; index < text.length; index += 1) {
		hash ^= text.charCodeAt(index);
		hash = Math.imul(hash, 16777619);
	}

	return hash >>> 0;
}

export function getPalePastelColor(value) {
	return paleProjectPalette[hashString(value) % paleProjectPalette.length];
}

const calendarSampleEntrySpecs = [
	{
		id: "entry-1",
		title: "Sprint Planning",
		category: "Meetings",
		start: monthEntryDate(2, 9, 7),
		end: monthEntryDate(2, 10, 38),
		color: "#dbeafe",
		status: null,
	},
	{
		id: "entry-2",
		title: "Feature Development",
		category: "Produkt",
		start: monthEntryDate(2, 10, 52),
		end: monthEntryDate(2, 14, 17),
		color: "#dcfce7",
		status: "warning",
	},
	{
		id: "entry-3",
		title: "Timesheet Cleanup",
		category: "Admin",
		start: monthEntryDate(3, 8, 43),
		end: monthEntryDate(3, 9, 26),
		color: "#e5e7eb",
		status: null,
	},
	{
		id: "entry-4",
		title: "Kunden Workshop",
		category: "Kunden",
		start: monthEntryDate(4, 13, 12),
		end: monthEntryDate(4, 16, 49),
		color: "#ede9fe",
		status: "error",
	},
	{
		id: "entry-5",
		title: "Deep Work: Reporting Export",
		category: "Fokus",
		start: monthEntryDate(5, 7, 58),
		end: monthEntryDate(5, 11, 44),
		color: "#ccfbf1",
		status: null,
	},
	{
		id: "entry-6",
		title: "Bug Triage",
		category: "Support",
		start: monthEntryDate(5, 10, 19),
		end: monthEntryDate(5, 11, 6),
		color: "#ffedd5",
		status: "warning",
	},
	{
		id: "entry-7",
		title: "Roadmap Sync",
		category: "Produkt",
		start: monthEntryDate(8, 14, 5),
		end: monthEntryDate(8, 15, 37),
		color: "#fef3c7",
		status: null,
	},
	{
		id: "entry-8",
		title: "Implementation Block",
		category: "Fokus",
		start: monthEntryDate(9, 9, 23),
		end: monthEntryDate(9, 13, 11),
		color: "#ccfbf1",
		status: "error",
	},
	{
		id: "entry-9",
		title: "1:1 Check-in",
		category: "Meetings",
		start: monthEntryDate(9, 11, 47),
		end: monthEntryDate(9, 12, 18),
		color: "#fee2e2",
		status: "warning",
	},
	{
		id: "entry-10",
		title: "Release Retro",
		category: "Meetings",
		start: monthEntryDate(11, 15, 9),
		end: monthEntryDate(11, 16, 3),
		color: "#cffafe",
		status: null,
	},
	{
		id: "entry-11",
		title: "Produkt Demo",
		category: "Produkt",
		start: monthEntryDate(12, 13, 29),
		end: monthEntryDate(12, 14, 54),
		color: "#fae8ff",
		status: null,
	},
	{
		id: "entry-12",
		title: "Invoice Review",
		category: "Admin",
		start: monthEntryDate(15, 8, 11),
		end: monthEntryDate(15, 9, 2),
		color: "#e5e7eb",
		status: "warning",
	},
	{
		id: "entry-13",
		title: "Customer Integration",
		category: "Kunden",
		start: monthEntryDate(15, 9, 38),
		end: monthEntryDate(15, 13, 52),
		color: "#d1fae5",
		status: "error",
	},
	{
		id: "entry-14",
		title: "Code Review Batch",
		category: "Produkt",
		start: monthEntryDate(16, 16, 17),
		end: monthEntryDate(16, 18, 8),
		color: "#dcfce7",
		status: null,
	},
	{
		id: "entry-15",
		title: "Production Support",
		category: "Support",
		start: monthEntryDate(18, 6, 34),
		end: monthEntryDate(18, 8, 21),
		color: "#ffedd5",
		status: "error",
	},
	{
		id: "entry-16",
		title: "Deep Work: Calendar Refactor",
		category: "Fokus",
		start: monthEntryDate(18, 8, 57),
		end: monthEntryDate(18, 12, 46),
		color: "#ccfbf1",
		status: null,
	},
	{
		id: "entry-17",
		title: "Planning Notes",
		category: "Admin",
		start: monthEntryDate(19, 12, 13),
		end: monthEntryDate(19, 12, 58),
		color: "#e5e7eb",
		status: "warning",
	},
	{
		id: "entry-18",
		title: "Stakeholder Review",
		category: "Meetings",
		start: monthEntryDate(22, 10, 4),
		end: monthEntryDate(22, 11, 22),
		color: "#dbeafe",
		status: null,
	},
	{
		id: "entry-19",
		title: "Analytics Investigation",
		category: "Fokus",
		start: monthEntryDate(22, 10, 41),
		end: monthEntryDate(22, 13, 7),
		color: "#ccfbf1",
		status: "warning",
	},
	{
		id: "entry-20",
		title: "Kunden Call Follow-up",
		category: "Kunden",
		start: monthEntryDate(23, 15, 46),
		end: monthEntryDate(23, 17, 19),
		color: "#ede9fe",
		status: "error",
	},
	{
		id: "entry-21",
		title: "Documentation Pass",
		category: "Produkt",
		start: monthEntryDate(25, 9, 16),
		end: monthEntryDate(25, 12, 29),
		color: "#fef3c7",
		status: null,
	},
	{
		id: "entry-22",
		title: "Support Escalation",
		category: "Support",
		start: monthEntryDate(26, 13, 3),
		end: monthEntryDate(26, 15, 51),
		color: "#ffedd5",
		status: "warning",
	},
	{
		id: "entry-23",
		title: "Monthly Timesheet Close",
		category: "Admin",
		start: monthEntryDate(28, 16, 22),
		end: monthEntryDate(28, 18, 37),
		color: "#e5e7eb",
		status: null,
	},
	{
		id: "entry-24",
		title: "Design Critique",
		category: "Meetings",
		start: monthEntryDate(5, 8, 35),
		end: monthEntryDate(5, 9, 20),
		color: "#dbeafe",
		status: "warning",
	},
	{
		id: "entry-25",
		title: "Customer QA Review",
		category: "Kunden",
		start: monthEntryDate(5, 9, 45),
		end: monthEntryDate(5, 10, 35),
		color: "#ede9fe",
		status: "error",
	},
	{
		id: "entry-26",
		title: "Release Checklist",
		category: "Produkt",
		start: monthEntryDate(5, 12, 10),
		end: monthEntryDate(5, 12, 55),
		color: "#dcfce7",
		status: null,
	},
	{
		id: "entry-27",
		title: "Incident Follow-up",
		category: "Support",
		start: monthEntryDate(5, 13, 20),
		end: monthEntryDate(5, 14, 5),
		color: "#ffedd5",
		status: "warning",
	},
	{
		id: "entry-28",
		title: "Spec Refinement",
		category: "Produkt",
		start: monthEntryDate(5, 14, 30),
		end: monthEntryDate(5, 15, 15),
		color: "#fef3c7",
		status: null,
	},
	{
		id: "entry-29",
		title: "Inbox Zero",
		category: "Admin",
		start: monthEntryDate(5, 16, 5),
		end: monthEntryDate(5, 16, 50),
		color: "#e5e7eb",
		status: "error",
	},
	{
		id: "entry-30",
		title: "Partner Sync",
		category: "Kunden",
		start: monthEntryDate(15, 7, 30),
		end: monthEntryDate(15, 8, 0),
		color: "#ede9fe",
		status: null,
	},
	{
		id: "entry-31",
		title: "Metrics Review",
		category: "Meetings",
		start: monthEntryDate(15, 10, 10),
		end: monthEntryDate(15, 10, 55),
		color: "#dbeafe",
		status: "warning",
	},
	{
		id: "entry-32",
		title: "Support Handoff",
		category: "Support",
		start: monthEntryDate(15, 11, 20),
		end: monthEntryDate(15, 12, 5),
		color: "#ffedd5",
		status: "error",
	},
	{
		id: "entry-33",
		title: "API Contract Review",
		category: "Produkt",
		start: monthEntryDate(15, 14, 15),
		end: monthEntryDate(15, 15, 5),
		color: "#dcfce7",
		status: null,
	},
	{
		id: "entry-34",
		title: "Focus Buffer",
		category: "Fokus",
		start: monthEntryDate(15, 15, 30),
		end: monthEntryDate(15, 16, 20),
		color: "#ccfbf1",
		status: "warning",
	},
	{
		id: "entry-35",
		title: "Admin Sweep",
		category: "Admin",
		start: monthEntryDate(15, 17, 0),
		end: monthEntryDate(15, 17, 45),
		color: "#e5e7eb",
		status: null,
	},
];

export const calendarSampleEntries = calendarSampleEntrySpecs.map((entry) => ({
	...entry,
	color: getPalePastelColor(entry.category),
}));

export const categoryFilters = [
	"Alle",
	"Fokus",
	"Meetings",
	"Produkt",
	"Kunden",
	"Support",
	"Admin",
];

export function updateCalendarSampleEntryTime(entries, { id, start, end }) {
	return entries.map((entry) => (entry.id === id ? { ...entry, start, end } : entry));
}
